# Generated by Django 6.1.1 on 2026-09-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('RESTOCK', 'Restock'), ('DAMAGE', 'Damage'), ('WASTE', 'Waste')], max_length=20),
        ),
    ]
